# Application details
server.port=8080
spring.application.name=agri-backend

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/agrimarket
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Drivermv,

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Custom security configuration
# A secure 256-bit key in hex format for HS256 signing
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
# Token expiration time: 24 hours (in milliseconds)
jwt.expiration=86400000
